### ISSUE TITLE
Exception creating domain in Azure

### ISSUE THREAD

**Issue by Migu3lB** [Azure-Samples/app-service-dotnet-scale-web-apps#5]
An exception is being thrown when trying to create the domain in azure. A '**BadRequest**' response is returned

### Error Image

![image](https://user-images.githubusercontent.com/5686717/143683239-caeef3fe-5f36-4e8d-b100-113aaaeabc4c.png)

### Exception Details

Microsoft.Azure.Management.AppService.Fluent.Models.DefaultErrorResponseException
  HResult=0x80131500
  Message=Operation returned an invalid status code 'BadRequest'
  Source=Microsoft.Azure.Management.AppService.Fluent
  StackTrace:
   at Microsoft.Azure.Management.AppService.Fluent.DomainsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.DomainsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.DomainsOperationsExtensions.<CreateOrUpdateAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.AppService.Fluent.AppServiceDomainImpl.<CreateResourceAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Create()
   at ManageWebAppWithTrafficManager.Program.RunSample(IAzure azure) in C:\....\source\repos\app-service-dotnet-scale-web-apps\Program.cs:line 59

  This exception was originally thrown at this call stack:
    [External Code]
    ManageWebAppWithTrafficManager.Program.RunSample(Microsoft.Azure.Management.Fluent.IAzure) in Program.cs

Thanks.

**Comment by Jayz58** [comment]
I'm also getting this error. Does anyone have the correct code?
